DROP TABLE IF EXISTS Nation;
DROP TABLE IF EXISTS Year;
DROP TABLE IF EXISTS Finances;
DROP TABLE IF EXISTS NetCon;
DROP TABLE IF EXISTS QoL;
DROP TABLE IF EXISTS Sustainability;
DROP TABLE IF EXISTS Energy;
DROP TABLE IF EXISTS Population;
